### ISSUE TITLE
Bidali atala diseinatu!

### ISSUE THREAD

**Issue by iunetrecet** [GISAElkartea/tresna-kutxa#41]

**Comment by umazalakain** [comment]
Erroreak daudela esaten duen paragrafotxoa hobe dehigarria egiten badugu

**Comment by iunetrecet** [comment]
Gehitu beharreko gauzak:
- Hizkuntzak tab moduan jarri

**Comment by iunetrecet** [comment]
Tabetatik mugitzen zeranean, inputak ez dira defektuz agerten

**Comment by iunetrecet** [comment]
eta sartzen zeranean gainera ez dago dagokion hizkuntza aktibatua, klik egin behar diozu aktibatzeko, nahiz eta inputa bai agertu
